### PR TITLE
Restore time_sync module on macOS

### PR DESCRIPTION
**Pull request by ludwigschwardt**
MacOS does not have the `adjtimex` system call. As a result we have stripped out the entire `time_sync` module on non-Linux platforms.

However, packages like katsdpcontroller need the `ClockState` enum without the rest. Instead of spreading the complications, restore the `time_sync` module with a fake `adjtimex` instead.

It returns the correct time but with artificially large errors in the absence of real values (and the status is always "OK").

[This was a leftover from the beginning of the year when I wanted to test katsdpcontroller on my laptop. Nearly forgot about it - it was lurking in my working copy for months 🙂 ]

### CODE REVIEW

**Review by bmerry — CHANGES_REQUESTED** [review]
I'm not wild about this approach, because it means the sensors will assert things that are just made up, rather than reporting that the values can't be measured. The only meaningful thing it returns is the current time, and that's not even reported as a sensor value. My preference would be
- the dummy `adjtimex()` function raises `NotImplementedError`
- `TimeSyncUpdater` catches `NotImplementedError` and responds by setting all the sensors to `inactive`.

Only a couple of tests would need to be disabled on MacOS. If you also added a test that mocked in the NotImplemented implementation and checked the response, you could get test coverage of that fallback on every OS.

File: src/aiokatcp/adjtimex.py [hunk 1]
```diff
@@ -142,6 +179,6 @@ def get_adjtimex() -> Tuple[int, Timex]:
         Clock information
     """
     timex = Timex()
-    timex.mode = 0
+    timex.modes = 0
```
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply src/aiokatcp/adjtimex.py:182]: I suspect the default `modes` member was probably already 0, and this line just silently added another superfluous `mode` member.

File: src/aiokatcp/adjtimex.py [hunk 2]
```diff
@@ -117,18 +123,49 @@ class Timex(ctypes.Structure):
...
-adjtimex.errcheck = _errcheck  # type: ignore
+try:
+    _libc = ctypes.CDLL("libc.so.6", use_errno=True)
+except OSError:
+    pass
+else:
+    adjtimex = _libc.adjtimex  # noqa: F811
+    adjtimex.argtypes = [ctypes.POINTER(Timex)]  # type: ignore[attr-defined]
+    adjtimex.restype = ctypes.c_int  # type: ignore[attr-defined]
+    adjtimex.errcheck = _errcheck  # type: ignore[attr-defined]
```
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply src/aiokatcp/adjtimex.py:168]: Good point. I like the Bruce-mypy tag-team clothesline 🤼‍♂️  I wanted to generate an AI picture of the event but Dall-E failed me 😂

File: .github/workflows/test.yml [hunk 3]
```diff
@@ -13,7 +13,6 @@ jobs:
         python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
         include:
           - python-version: "3.10"
-            os: ubuntu-20.04
```
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply .github/workflows/test.yml:16]: Sadly it doesn't, which is why some folks recommend `codecov` instead. See e.g. lemurheavy/coveralls-public#613, which started in 2015 and is still going strong in 2023.

[the remark this answers is not in the document]
Comment (bmerry) [reply .github/workflows/test.yml:16]: > See e.g. https://github.com/lemurheavy/coveralls-public/issues/613, which started in 2015 and is still going strong in 2023.

That seems to be related to using different CI systems though. In theory I think it's possible to do the merge within Github Actions. On the other hand, I think my suggestion of having tests that use mocking to force use of the fallback implementation will make it possible for Linux to have a superset of MacOS coverage, in which case I don't think it's necessary to run coverage on MacOS at all.

> By the way, I just reverted it to the way it was before https://github.com/ska-sa/aiokatcp/pull/70.

Not exactly the way it was, because before #70 the tests weren't run on MacOS at all.

[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply .github/workflows/test.yml:16]: > Not exactly the way it was...

Right, forgot about that part :-)

As I discovered after you replied (blame GitHub flakiness :-)), it looks like the merge does happen. I'll try that route first.

File: src/aiokatcp/adjtimex.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply src/aiokatcp/adjtimex.py:168]: To be fair: mypy didn't like the assignment to attributes, which apparently did not bother it before (there was only one `type: ignore` on the last line, but now they all complained).  It was actually flake8 with the issue [Redefinition of unused name from line n](https://www.flake8rules.com/rules/F811.html).

**Comment by ludwigschwardt** [comment]
Thanks! I've pushed a new version incorporating your suggestions.

I can't figure out the failing tests though. It fails on py311 on both Linux and macOS, and it seems to be unrelated to my fixes. In fact, if I rerun the tests on an older commit that previously passed, it now fails there too 🤔  It also doesn't fail on my laptop. Rerunning these tests several times doesn't help, so it's not just a random fluke.

It's complaining about a closed event loop in `TestUnclosedClient`.

**Comment by bmerry** [comment]
> Thanks! I've pushed a new version incorporating your suggestions.
> 
> I can't figure out the failing tests though. It fails on py311 on both Linux and macOS, and it seems to be unrelated to my fixes. In fact, if I rerun the tests on an older commit that previously passed, it now fails there too 🤔 It also doesn't fail on my laptop. Rerunning these tests several times doesn't help, so it's not just a random fluke.
> 
> It's complaining about a closed event loop in `TestUnclosedClient`.

The Python 3.11 failures I think are caused by https://github.com/python/cpython/pull/107650, which got backported to 3.11. We'll need to investigate to see if this is a regression in Python or something that we should be handling better.

**Comment by bmerry** [comment]
> The Python 3.11 failures I think are caused by [python/cpython#107650](https://github.com/python/cpython/pull/107650), which got backported to 3.11. We'll need to investigate to see if this is a regression in Python or something that we should be handling better.

I don't think that should hold up this PR, but we should investigate it before making a new release.

**Comment by bmerry** [comment]
I've opened NGC-1089 for the Python 3.11 issue.

**Review by bmerry — CHANGES_REQUESTED** [review]

File: .github/workflows/test.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply .github/workflows/test.yml:16]: It does. The latest results claim that `Coverage decreased (-0.1%) to 93.406%`. If you drill down to the details, you'd see two jobs (linux + macOS) and a merged total of 93.41%:

Screenshot 2023-09-11 at 11 56 34

Each job has poor coverage on `adjtimex.py` but the combined coverage is 95.52%.

[the remark this answers is not in the document]
Comment (bmerry) [reply .github/workflows/test.yml:16]: Nice!

**Comment by bmerry** [comment]
Also don't forget to bump the year in the copyright notice.

File: tests/test_time_sync.py [hunk 4]
```diff
@@ -69,15 +66,34 @@ def mock_adjtimex(mocker, request) -> None:
...
+    sys.platform.startswith("linux"),
+    reason="Check unimplemented adjtimex on non-Linux systems only",
+)
+
+
+@pytest.mark.parametrize(
+    ("expected_status",),
+    [
+        pytest.param(Sensor.Status.NOMINAL, marks=_linux),
+        pytest.param(Sensor.Status.INACTIVE, marks=_non_linux),
```
[the remark this answers is not in the document]
Comment (ludwigschwardt) [reply tests/test_time_sync.py:83]: I'm not getting away here :-) Done!

**Comment by ludwigschwardt** [comment]
OK, after many force-pushes I'm ready for another round 😅

File: .gitignore [hunk 5]
```diff
@@ -7,3 +7,6 @@
 src/aiokatcp.egg-info
 *.pyc
 __pycache__
+
+# macOS detritus
+.DS_Store
```
Comment (bmerry) [inline .gitignore:12]: I feel like that should go into your global `core.excludesfile` rather than here, because it's specific to your development environment rather than specific to the repository.

File: tests/test_time_sync.py [hunk 6]
```diff
@@ -69,15 +66,40 @@ def mock_adjtimex(mocker, request) -> None:
...
+    "expected_status",
+    [
+        pytest.param(Sensor.Status.NOMINAL, marks=_linux),
+        pytest.param(Sensor.Status.INACTIVE, marks=_non_linux),
+    ],
+)
+def test_smoke(
+    sensors: SensorSet, updater: TimeSyncUpdater, expected_status: Sensor.Status
+) -> None:
+    """Test with real adjtimex on Linux to ensure it interacts cleanly with kernel."""
```
Comment (bmerry) [inline tests/test_time_sync.py:95]: Not sure that docstring is accurate. It only covers one of the two parametrisations.

Come to think of it, I'm not sure parametrisation is really necessary, since they're a partition. You could just write
```python
expected_status = Sensor.Status.NOMINAL if sys.platform == "linux" else Sensor.Status.INACTIVE
```
inside the test function.

File: tests/test_time_sync.py [hunk 7]
```diff
@@ -93,3 +115,14 @@ def test_mocked(sensors: SensorSet, updater: TimeSyncUpdater, mock_adjtimex) ->
...
+
+def test_no_adjtimex(sensors: SensorSet, updater: TimeSyncUpdater, mock_no_adjtimex):
+    """Pretend that adjtimex is absent and test that it is handled correctly."""
+    updater.update()
+    assert isinstance(sensors["ntp.esterror"].value, float)
+    assert isinstance(sensors["ntp.maxerror"].value, float)
+    assert isinstance(sensors["ntp.state"].value, ClockState)
+    for sensor in sensors.values():
+        # Check that it actually got updated
+        assert sensor.status == Sensor.Status.INACTIVE
```
Comment (bmerry) [inline tests/test_time_sync.py:128]: A lot of code duplication here. I'd suggest either:
- Parametrise `test_smoke` with a boolean that says whether to mock, and conditionally use `mocker` inside the test; or
- Factor out a helper function that does all the work of the test, and have the test functions call it.

**Review by bmerry — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 5 above)
Comment (ludwigschwardt) [reply .gitignore:12]: Thanks, I did not know about that file... I merely cargo-culted some other repo's ignores (katpoint, etc). Much better idea!

File: tests/test_time_sync.py (hunk 6 above)
Comment (ludwigschwardt) [reply tests/test_time_sync.py:95]: Thanks, I missed the partition. I originally had tests for linux and darwin until I merged them.

File: tests/test_time_sync.py (hunk 7 above)
Comment (ludwigschwardt) [reply tests/test_time_sync.py:128]: I've gone for option 1 and lost 20 lines.

**Comment by ludwigschwardt** [comment]
Thanks for the suggestions! You can check again.

**Review by bmerry — APPROVED** [review]
LGTM. Go ahead and merge - there is a separate ticket for the Python 3.11 failures.
